### PR TITLE
improve typehints for solve

### PR DESCRIPTION
**Pull request by rkaminsk**

### CODE REVIEW

**Comment by rkaminsk** [comment]
@jorgefandinno can you give this one a try to see if mypy/completion is working as expected now.

**Comment by jorgefandinno** [comment]
> @jorgefandinno can you give this one a try to see if mypy/completion is working as expected now.

Can I install this from conda or do I need to build it from source?

**Comment by rkaminsk** [comment]
You can install from the potassco/label/dev channel.

**Comment by jorgefandinno** [comment]
It works

**Pull request merged**
