### PR TITLE
Issues with clingo’s unit tests

### PR DESCRIPTION
**Pull request by pluehne**
Fixes two issues related to clingo’s unit tests.

### CODE REVIEW

**Comment by rkaminsk** [comment]
Hi, which compiler complains about the zero sized arrays? I tested with clang-3.4, clang-3.5, clang-3.8, gcc-4.9, and gcc-6.1 and none of them even issued a warning (have not checked the standard though).

**Comment by pluehne** [comment]
My gcc version is: 6.1.1 20160501 (GCC). gcc fails with the following error:

```
c++ -o build/debug/libclingo/tests/clingo.o -c -std=c++11 -O0 -g -Wall -W -pedantic -DWITH_LUA=1 -DWITH_PYTHON=1 -I/usr/include/python3.5m -Ilibclingo -Ilibgringo -Ibuild/debug/libgringo/src -Ilibgringo/src -Iliblp -Iliblp/src -Ilibclasp -Ilibclasp/src -Ilibprogram_opts -Ilibprogram_opts/src -Iliblp -Iliblp/src libclingo/tests/clingo.cc
libclingo/tests/clingo.cc:39:2: warning: extra ';' [-Wpedantic]
 };
  ^
libclingo/tests/clingo.cc: In function 'void ____C_A_T_C_H____T_E_S_T____49()':
libclingo/tests/clingo.cc:60:50: error: zero-size array 'values_base'
                 clingo_symbol_t values_base[] = {};
                                                  ^
libclingo/tests/clingo.cc:64:53: error: zero-size array 'ass'
                 clingo_symbolic_literal_t ass[] = { };
```
```

**Comment by pluehne** [comment]
I could reproduce the error on another machine with the same gcc version.

**Comment by rkaminsk** [comment]
I checked, there is the widely implemented extension for zero sized arrays at the end of structs/classes. Looks like other usages of such arrays result in undefined behaviour. It is probably best to simply use a nullptr there.

**Comment by pluehne** [comment]
nullptr will not work here because `sizeof(values_base)` is 0 for a null-sized array but 1 for `nullptr`.

**Comment by rkaminsk** [comment]
Simply replace it with 0. :)

**Comment by pluehne** [comment]
Here you are :).

**Comment by pluehne** [comment]
Sorry, please wait with merging until I fix the incorrect e-mail address provided in my last commit …

**Comment by pluehne** [comment]
Done. You may merge my changes now if you consider them fine :).

**Comment by rkaminsk** [comment]
Thanks so much!

**Pull request merged**
